services:

  postgres:
    image: postgres:16
    container_name: futurekawa-postgres
    environment:
      POSTGRES_DB: futurekawa
      POSTGRES_USER: futurekawa
      POSTGRES_PASSWORD: futurekawa
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U futurekawa -d futurekawa"]
      interval: 5s
      timeout: 5s
      retries: 10

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: futurekawa-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config

  # backend-country:
  #   build: ./backend-country
  #   container_name: backend-country
  #   ports:
  #     - "8001:8000"

  backend-country:
    build: ./backend-country
    container_name: backend-country
    ports:
    - "8001:8000"
    environment:
      DATABASE_URL: postgresql://futurekawa:futurekawa@postgres:5432/futurekawa
      MQTT_HOST: mosquitto
      MQTT_PORT: 1883
      MQTT_TOPIC_MEASURES: futurekawa/equateur/measures
      MQTT_TOPIC_ALERTS: futurekawa/equateur/alerts
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      ALERT_EMAIL_TO: ${ALERT_EMAIL_TO}
      PYTHONUNBUFFERED: 1
      
    depends_on:
      postgres:
        condition: service_healthy
      mosquitto:
        condition: service_started

  backend-central:
    build: ./backend-central
    container_name: backend-central
    ports:
      - "8000:8000"
    environment:
      COUNTRY_BACKEND_URL: http://backend-country:8000
    depends_on:
      - backend-country

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:80"